# bar
bar_enabled = 1
bar_enabled_ws[1] = 1
bar_border_width = 1
bar_border[1] = rgb:00/00/00
bar_border_unfocus[1] = rgb:00/00/00
bar_color[1] = rgb:00/00/00
bar_color_selected[1] = rgb:00/00/00
bar_font_color[2] = rgb:248/248/255
bar_font_color_selected = rgb:248/248/255
bar_font = JetBrainsMonoMedium Nerd Font:pixelsize=15:antialias=true
bar_action = ~/.local/bin/baraction.sh
bar_action_expand = g
bar_justify = left
bar_format = +|L+<+S+<+F+<+L+2<+<絛+<:+M+< 类+<+W+|R+A %a, %d %b %R
bar_at_bottom = 0
stack_enabled = 1
clock_enabled = 1
clock_format = %a, %d %b %R
iconic_enabled = 1
maximize_hide_bar = 0
window_class_enabled = 1
window_instance_enabled = 1
window_name_enabled = 1
verbose_layout = 1
urgent_enabled = 1

# borders
border_width = 1
color_focus = darkgrey
color_unfocus = rgb:128/128/128

# keybindigs
keyboard_mapping = ~/.config/spectrwm/spectrwm-keys.conf
modkey = Mod4

# gaps
region_padding = 8
tile_gap = 10

# misc
workspace_limit = 9
workspace_indicator = listactive,listcurrent,markcurrent,markurgent
dialog_ratio = 0.4
disable_border = 1

# programs
program[term]               = st
program[lock]               = slock
program[menu]               = dmenu_tuxy
program[flameshot]          = flameshot gui
bind[flameshot]             = Print
program[qutebrowser]        = qutebrowser
bind[qutebrowser]           = MOD+w
program[qute-priv]          = qutebrowser --target private-window
bind[qute-priv]             = MOD+shift+w
program[firefox]            = firefox
bind[firefox]               = MOD+y
program[firefox-priv]       = firefox --private-window
bind[firefox-priv]          = MOD+shift+y
#program[displayselect]      = displayselect
#bind[displayselect]         = MOD+F3
#program[dmenumount]         = dmenumount
#bind[dmenumount]            = MOD+F9
#program[dmenuumount]        = dmenuumount
#bind[dmenuumount]           = MOD+F10
program[screenshots]        = screenshots
bind[screenshots]           = MOD+z
#program[ranger]             = urxvtc -e ranger
#bind[ranger]                = MOD+e
program[sound_increase]	    = pactl set-sink-volume @DEFAULT_SINK@ +10%
bind[sound_increase]	    = XF86AudioRaiseVolume
program[sound_decrease]	    = pactl set-sink-volume @DEFAULT_SINK@ -10%
bind[sound_decrease]	    = XF86AudioLowerVolume
program[sound_mute]	    = pactl set-sink-mute @DEFAULT_SINK@ toggle
bind[sound_mute]	    = XF86AudioMute
program[mic_mute]	    = pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind[mic_mute]	    = XF86AudioMicMute
program[brightness_increase] = xbacklight -inc 10
bind[brightness_increase]   = XF86MonBrightnessUp
program[brightness_decrease] = xbacklight -dec 10
bind[brightness_decrease]   = XF86MonBrightnessDown

# Layouts
#layout	= ws[8]:0:0:0:0:floating

# Quirks
quirk[mpv] = FLOAT + FULLSCREEN + FOCUSPREV
quirk[firefox:Navigator] = FLOAT + FOCUSPREV
quirk[qutebrowser] = WS[2]
quirk[TelegramDesktop] = WS[3]
quirk[discord] = WS[3]
quirk[Signal] = WS[3]
quirk[Logseq] = WS[6]
quirk[Virt-manager] = WS[7]
quirk[.*zap.*] = WS[8] + FLOAT + FOCUSPREV
